export * from './authentication.api';
import { AuthenticationApi } from './authentication.api';
export * from './chefManagement.api';
import { ChefManagementApi } from './chefManagement.api';
export * from './customerManagement.api';
import { CustomerManagementApi } from './customerManagement.api';
export * from './dashboard.api';
import { DashboardApi } from './dashboard.api';
export * from './entities.api';
import { EntitiesApi } from './entities.api';
export * from './history.api';
import { HistoryApi } from './history.api';
export * from './kitchenRules.api';
import { KitchenRulesApi } from './kitchenRules.api';
export * from './mealPlanning.api';
import { MealPlanningApi } from './mealPlanning.api';
export * from './meals.api';
import { MealsApi } from './meals.api';
export * from './newsletter.api';
import { NewsletterApi } from './newsletter.api';
export * from './notifications.api';
import { NotificationsApi } from './notifications.api';
export * from './orders.api';
import { OrdersApi } from './orders.api';
export * from './payments.api';
import { PaymentsApi } from './payments.api';
export * from './stock.api';
import { StockApi } from './stock.api';
export const APIS = [AuthenticationApi, ChefManagementApi, CustomerManagementApi, DashboardApi, EntitiesApi, HistoryApi, KitchenRulesApi, MealPlanningApi, MealsApi, NewsletterApi, NotificationsApi, OrdersApi, PaymentsApi, StockApi];
