/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ErrorResponse } from '../model/errorResponse';
// @ts-ignore
import { PlanningAvailableMealsGet200Response } from '../model/planningAvailableMealsGet200Response';
// @ts-ignore
import { PlanningMealPlansGet200Response } from '../model/planningMealPlansGet200Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdCheckResourcesGet200Response } from '../model/planningMealPlansMealPlanIdCheckResourcesGet200Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdCheckStockGet200Response } from '../model/planningMealPlansMealPlanIdCheckStockGet200Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdDelete200Response } from '../model/planningMealPlansMealPlanIdDelete200Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdDuplicatePost201Response } from '../model/planningMealPlansMealPlanIdDuplicatePost201Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdDuplicatePostRequest } from '../model/planningMealPlansMealPlanIdDuplicatePostRequest';
// @ts-ignore
import { PlanningMealPlansMealPlanIdGet200Response } from '../model/planningMealPlansMealPlanIdGet200Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdPut200Response } from '../model/planningMealPlansMealPlanIdPut200Response';
// @ts-ignore
import { PlanningMealPlansMealPlanIdPutRequest } from '../model/planningMealPlansMealPlanIdPutRequest';
// @ts-ignore
import { PlanningMealPlansPost201Response } from '../model/planningMealPlansPost201Response';
// @ts-ignore
import { PlanningMealPlansPostRequest } from '../model/planningMealPlansPostRequest';
// @ts-ignore
import { ValidationError } from '../model/validationError';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class MealPlanningApi extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get available meals for planning
     * Retrieve all meals that are available for meal planning
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningAvailableMealsGet(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningAvailableMealsGet200Response>;
    public planningAvailableMealsGet(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningAvailableMealsGet200Response>>;
    public planningAvailableMealsGet(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningAvailableMealsGet200Response>>;
    public planningAvailableMealsGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/available-meals`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningAvailableMealsGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get meal plans with filters
     * Retrieve meal plans based on date, type, or date range filters
     * @param type Filter by plan type
     * @param date Specific date to search for (YYYY-MM-DD)
     * @param startDate Start date for range search (YYYY-MM-DD)
     * @param endDate End date for range search (YYYY-MM-DD)
     * @param mealTimeType Type of meal type
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansGet(type?: 'day' | 'week', date?: string, startDate?: string, endDate?: string, mealTimeType?: 'breakfast' | 'lunch' | 'dinner', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansGet200Response>;
    public planningMealPlansGet(type?: 'day' | 'week', date?: string, startDate?: string, endDate?: string, mealTimeType?: 'breakfast' | 'lunch' | 'dinner', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansGet200Response>>;
    public planningMealPlansGet(type?: 'day' | 'week', date?: string, startDate?: string, endDate?: string, mealTimeType?: 'breakfast' | 'lunch' | 'dinner', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansGet200Response>>;
    public planningMealPlansGet(type?: 'day' | 'week', date?: string, startDate?: string, endDate?: string, mealTimeType?: 'breakfast' | 'lunch' | 'dinner', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>type, 'type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>date, 'date');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startDate, 'startDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endDate, 'endDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>mealTimeType, 'mealTimeType');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Check resources for meal plan
     * Check if all required resources are available for a specific meal plan
     * @param mealPlanId Meal plan ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansMealPlanIdCheckResourcesGet(mealPlanId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansMealPlanIdCheckResourcesGet200Response>;
    public planningMealPlansMealPlanIdCheckResourcesGet(mealPlanId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansMealPlanIdCheckResourcesGet200Response>>;
    public planningMealPlansMealPlanIdCheckResourcesGet(mealPlanId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansMealPlanIdCheckResourcesGet200Response>>;
    public planningMealPlansMealPlanIdCheckResourcesGet(mealPlanId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (mealPlanId === null || mealPlanId === undefined) {
            throw new Error('Required parameter mealPlanId was null or undefined when calling planningMealPlansMealPlanIdCheckResourcesGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans/${this.configuration.encodeParam({name: "mealPlanId", value: mealPlanId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/check-resources`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansMealPlanIdCheckResourcesGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Check stock for meal plan
     * Check if all required ingredients are available for a specific meal plan
     * @param mealPlanId Meal plan ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansMealPlanIdCheckStockGet(mealPlanId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansMealPlanIdCheckStockGet200Response>;
    public planningMealPlansMealPlanIdCheckStockGet(mealPlanId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansMealPlanIdCheckStockGet200Response>>;
    public planningMealPlansMealPlanIdCheckStockGet(mealPlanId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansMealPlanIdCheckStockGet200Response>>;
    public planningMealPlansMealPlanIdCheckStockGet(mealPlanId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (mealPlanId === null || mealPlanId === undefined) {
            throw new Error('Required parameter mealPlanId was null or undefined when calling planningMealPlansMealPlanIdCheckStockGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans/${this.configuration.encodeParam({name: "mealPlanId", value: mealPlanId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/check-stock`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansMealPlanIdCheckStockGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete meal plan
     * Delete a meal plan. Stock will be automatically restored from all meals in the plan. The restoration is proportional to the servings that were planned.**
     * @param mealPlanId Meal plan ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansMealPlanIdDelete(mealPlanId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansMealPlanIdDelete200Response>;
    public planningMealPlansMealPlanIdDelete(mealPlanId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansMealPlanIdDelete200Response>>;
    public planningMealPlansMealPlanIdDelete(mealPlanId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansMealPlanIdDelete200Response>>;
    public planningMealPlansMealPlanIdDelete(mealPlanId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (mealPlanId === null || mealPlanId === undefined) {
            throw new Error('Required parameter mealPlanId was null or undefined when calling planningMealPlansMealPlanIdDelete.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans/${this.configuration.encodeParam({name: "mealPlanId", value: mealPlanId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansMealPlanIdDelete200Response>('delete', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Duplicate meal plan
     * Create a copy of an existing meal plan
     * @param mealPlanId Meal plan ID to duplicate
     * @param planningMealPlansMealPlanIdDuplicatePostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansMealPlanIdDuplicatePost(mealPlanId: string, planningMealPlansMealPlanIdDuplicatePostRequest: PlanningMealPlansMealPlanIdDuplicatePostRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansMealPlanIdDuplicatePost201Response>;
    public planningMealPlansMealPlanIdDuplicatePost(mealPlanId: string, planningMealPlansMealPlanIdDuplicatePostRequest: PlanningMealPlansMealPlanIdDuplicatePostRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansMealPlanIdDuplicatePost201Response>>;
    public planningMealPlansMealPlanIdDuplicatePost(mealPlanId: string, planningMealPlansMealPlanIdDuplicatePostRequest: PlanningMealPlansMealPlanIdDuplicatePostRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansMealPlanIdDuplicatePost201Response>>;
    public planningMealPlansMealPlanIdDuplicatePost(mealPlanId: string, planningMealPlansMealPlanIdDuplicatePostRequest: PlanningMealPlansMealPlanIdDuplicatePostRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (mealPlanId === null || mealPlanId === undefined) {
            throw new Error('Required parameter mealPlanId was null or undefined when calling planningMealPlansMealPlanIdDuplicatePost.');
        }
        if (planningMealPlansMealPlanIdDuplicatePostRequest === null || planningMealPlansMealPlanIdDuplicatePostRequest === undefined) {
            throw new Error('Required parameter planningMealPlansMealPlanIdDuplicatePostRequest was null or undefined when calling planningMealPlansMealPlanIdDuplicatePost.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans/${this.configuration.encodeParam({name: "mealPlanId", value: mealPlanId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/duplicate`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansMealPlanIdDuplicatePost201Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: planningMealPlansMealPlanIdDuplicatePostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get meal plan by ID
     * Retrieve a specific meal plan with all details
     * @param mealPlanId Meal plan ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansMealPlanIdGet(mealPlanId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansMealPlanIdGet200Response>;
    public planningMealPlansMealPlanIdGet(mealPlanId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansMealPlanIdGet200Response>>;
    public planningMealPlansMealPlanIdGet(mealPlanId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansMealPlanIdGet200Response>>;
    public planningMealPlansMealPlanIdGet(mealPlanId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (mealPlanId === null || mealPlanId === undefined) {
            throw new Error('Required parameter mealPlanId was null or undefined when calling planningMealPlansMealPlanIdGet.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans/${this.configuration.encodeParam({name: "mealPlanId", value: mealPlanId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansMealPlanIdGet200Response>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update meal plan
     * Update an existing meal plan. Stock will be automatically adjusted - restored from old meals and deducted from new meals. The adjustment is proportional to the servings requested.**
     * @param mealPlanId Meal plan ID
     * @param planningMealPlansMealPlanIdPutRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansMealPlanIdPut(mealPlanId: string, planningMealPlansMealPlanIdPutRequest: PlanningMealPlansMealPlanIdPutRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansMealPlanIdPut200Response>;
    public planningMealPlansMealPlanIdPut(mealPlanId: string, planningMealPlansMealPlanIdPutRequest: PlanningMealPlansMealPlanIdPutRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansMealPlanIdPut200Response>>;
    public planningMealPlansMealPlanIdPut(mealPlanId: string, planningMealPlansMealPlanIdPutRequest: PlanningMealPlansMealPlanIdPutRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansMealPlanIdPut200Response>>;
    public planningMealPlansMealPlanIdPut(mealPlanId: string, planningMealPlansMealPlanIdPutRequest: PlanningMealPlansMealPlanIdPutRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (mealPlanId === null || mealPlanId === undefined) {
            throw new Error('Required parameter mealPlanId was null or undefined when calling planningMealPlansMealPlanIdPut.');
        }
        if (planningMealPlansMealPlanIdPutRequest === null || planningMealPlansMealPlanIdPutRequest === undefined) {
            throw new Error('Required parameter planningMealPlansMealPlanIdPutRequest was null or undefined when calling planningMealPlansMealPlanIdPut.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans/${this.configuration.encodeParam({name: "mealPlanId", value: mealPlanId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansMealPlanIdPut200Response>('put', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: planningMealPlansMealPlanIdPutRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create meal plan (daily or weekly)
     * Create a new meal plan for a specific day or week with assigned meals and staff. Stock will be automatically deducted from ingredients when the meal plan is created. The deduction is proportional to the servings requested - if a meal serves 10 people and you request 5 servings, only 50% of the ingredient quantities will be deducted.**
     * @param planningMealPlansPostRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public planningMealPlansPost(planningMealPlansPostRequest: PlanningMealPlansPostRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<PlanningMealPlansPost201Response>;
    public planningMealPlansPost(planningMealPlansPostRequest: PlanningMealPlansPostRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<PlanningMealPlansPost201Response>>;
    public planningMealPlansPost(planningMealPlansPostRequest: PlanningMealPlansPostRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<PlanningMealPlansPost201Response>>;
    public planningMealPlansPost(planningMealPlansPostRequest: PlanningMealPlansPostRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (planningMealPlansPostRequest === null || planningMealPlansPostRequest === undefined) {
            throw new Error('Required parameter planningMealPlansPostRequest was null or undefined when calling planningMealPlansPost.');
        }

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/planning/meal-plans`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<PlanningMealPlansPost201Response>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: planningMealPlansPostRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
