/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AllergenUpdate { 
    name?: string;
    description?: string;
    severity?: AllergenUpdate.SeverityEnum;
    isActive?: boolean;
}
export namespace AllergenUpdate {
    export const SeverityEnum = {
        Low: 'low',
        Medium: 'medium',
        High: 'high'
    } as const;
    export type SeverityEnum = typeof SeverityEnum[keyof typeof SeverityEnum];
}


