/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthForgotPasswordPost200ResponseData } from './authForgotPasswordPost200ResponseData';


export interface AuthForgotPasswordPost200Response { 
    success?: boolean;
    message?: string;
    data?: AuthForgotPasswordPost200ResponseData;
}

