/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealPlanItem } from './mealPlanItem';


export interface DailyMealPlan { 
    date: string;
    type: DailyMealPlan.TypeEnum;
    meals: Array<MealPlanItem>;
    assignedStaff: Array<string>;
    notes: string;
    createdBy: string;
}
export namespace DailyMealPlan {
    export const TypeEnum = {
        Day: 'day'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


