/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeleteResponseData } from './deleteResponseData';


export interface DeleteResponse { 
    success?: boolean;
    data?: DeleteResponseData;
    message?: string;
    statusCode?: number;
}

