/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KitchenRulesGet200ResponseData } from './kitchenRulesGet200ResponseData';


export interface KitchenRulesGet200Response { 
    success?: boolean;
    data?: KitchenRulesGet200ResponseData;
    message?: string;
    statusCode?: number;
}

