/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MealsGet200ResponseDataInnerAvailability { 
    available?: boolean;
    availableServings?: number;
    totalCost?: number;
    missingIngredients?: Array<string>;
    lowStockIngredients?: Array<string>;
}

