/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealsGet200ResponseDataInnerAvailability } from './mealsGet200ResponseDataInnerAvailability';
import { Category } from './category';


export interface MealsGet200ResponseDataInner { 
    _id?: string;
    title?: string;
    description?: string;
    servings?: number;
    price?: number;
    mealType?: MealsGet200ResponseDataInner.MealTypeEnum;
    category?: Category;
    images?: Array<string>;
    isActive?: boolean;
    allergens?: Array<object>;
    ingredients?: Array<object>;
    tags?: Array<object>;
    availability?: MealsGet200ResponseDataInnerAvailability;
}
export namespace MealsGet200ResponseDataInner {
    export const MealTypeEnum = {
        Breakfast: 'breakfast',
        Lunch: 'lunch',
        Dinner: 'dinner'
    } as const;
    export type MealTypeEnum = typeof MealTypeEnum[keyof typeof MealTypeEnum];
}


