/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealPlanCreateMealsInner } from './mealPlanCreateMealsInner';


export interface MealPlanCreate { 
    name: string;
    description: string;
    meals: Array<MealPlanCreateMealsInner>;
    startDate: string;
    endDate: string;
    isActive?: boolean;
}

