/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealPlanStockCheckDataMissingIngredientsInner } from './mealPlanStockCheckDataMissingIngredientsInner';


export interface MealPlanStockCheckData { 
    mealPlanId?: string;
    available?: boolean;
    missingIngredients?: Array<MealPlanStockCheckDataMissingIngredientsInner>;
}

