/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealPlanListResponseDataInner } from './mealPlanListResponseDataInner';


export interface MealPlanListResponse { 
    success?: boolean;
    data?: Array<MealPlanListResponseDataInner>;
}

