/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationSend { 
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification message
     */
    message: string;
    /**
     * Notification type
     */
    type: NotificationSend.TypeEnum;
    /**
     * Array of user IDs or \'all\' for all users
     */
    recipients: Array<string>;
    /**
     * Notification priority level
     */
    priority?: NotificationSend.PriorityEnum;
}
export namespace NotificationSend {
    export const TypeEnum = {
        Info: 'info',
        Warning: 'warning',
        Error: 'error',
        Success: 'success'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const PriorityEnum = {
        Low: 'low',
        Normal: 'normal',
        High: 'high'
    } as const;
    export type PriorityEnum = typeof PriorityEnum[keyof typeof PriorityEnum];
}


