/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationGet200ResponseDataInner { 
    _id?: string;
    title?: string;
    message?: string;
    type?: NotificationGet200ResponseDataInner.TypeEnum;
    isRead?: boolean;
    createdAt?: string;
}
export namespace NotificationGet200ResponseDataInner {
    export const TypeEnum = {
        Info: 'info',
        Warning: 'warning',
        Error: 'error',
        Success: 'success'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


