/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationGet200ResponseDataInner } from './notificationGet200ResponseDataInner';


export interface NotificationGet200Response { 
    success?: boolean;
    message?: string;
    data?: Array<NotificationGet200ResponseDataInner>;
}

