/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderHistorySummaryData } from './orderHistorySummaryData';


export interface OrderHistorySummary { 
    success?: boolean;
    data?: OrderHistorySummaryData;
}

