/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderStatusUpdate { 
    /**
     * New order status
     */
    status: OrderStatusUpdate.StatusEnum;
    /**
     * Additional notes about the status change (optional)
     */
    notes?: string;
}
export namespace OrderStatusUpdate {
    export const StatusEnum = {
        Pending: 'pending',
        Confirmed: 'confirmed',
        Preparing: 'preparing',
        Ready: 'ready',
        Delivered: 'delivered',
        Cancelled: 'cancelled'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


