/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentStripeIntentPaymentIdRefundPostRequest { 
    /**
     * The amount to refund. Must be a positive number and less than or equal to the refundable amount.
     */
    amount?: number;
    /**
     * Optional reason for the refund. Use \'duplicate\', \'fraudulent\', or \'requested_by_customer\' for Stripe, or provide a custom note.
     */
    reason?: string;
}

