/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentCreatePaymentDetails } from './paymentCreatePaymentDetails';


export interface PaymentCreate { 
    orderId: string;
    status: PaymentCreate.StatusEnum;
    paymentDetails: PaymentCreatePaymentDetails;
}
export namespace PaymentCreate {
    export const StatusEnum = {
        Pending: 'pending',
        Completed: 'completed',
        Failed: 'failed',
        Refunded: 'refunded'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


