/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentFees } from './paymentFees';
import { Address } from './address';
import { PaymentDetails } from './paymentDetails';


export interface Payment { 
    _id?: string;
    orderId?: string;
    customerId?: string;
    amount?: number;
    currency?: string;
    type?: string;
    method?: string;
    status?: Payment.StatusEnum;
    paymentDetails?: PaymentDetails;
    billingAddress?: Address;
    fees?: PaymentFees;
    createdAt?: string;
}
export namespace Payment {
    export const StatusEnum = {
        Pending: 'pending',
        Completed: 'completed',
        Failed: 'failed',
        Refunded: 'refunded'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


