/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanningMealPlansPostRequestMealsInner } from './planningMealPlansPostRequestMealsInner';


export interface PlanningMealPlansPostRequest { 
    /**
     * Date for daily plans (required when type is \'day\') (YYYY-MM-DD)
     */
    date?: string;
    /**
     * Start date for weekly plans (required when type is \'week\') (YYYY-MM-DD)
     */
    startDate?: string;
    /**
     * End date for weekly plans (required when type is \'week\') (YYYY-MM-DD)
     */
    endDate?: string;
    /**
     * Type of meal plan
     */
    type: PlanningMealPlansPostRequest.TypeEnum;
    /**
     * Type of meal plan time
     */
    mealTimeType?: PlanningMealPlansPostRequest.MealTimeTypeEnum;
    /**
     * Array of meals with their required servings
     */
    meals: Array<PlanningMealPlansPostRequestMealsInner>;
    /**
     * Array of user IDs for assigned staff
     */
    assignedStaff: Array<string>;
    /**
     * Additional notes for the meal plan
     */
    notes: string;
    /**
     * User ID of the creator
     */
    createdBy: string;
}
export namespace PlanningMealPlansPostRequest {
    export const TypeEnum = {
        Day: 'day',
        Week: 'week'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const MealTimeTypeEnum = {
        Breakfast: 'breakfast',
        Lunch: 'lunch',
        Dinner: 'dinner'
    } as const;
    export type MealTimeTypeEnum = typeof MealTimeTypeEnum[keyof typeof MealTimeTypeEnum];
}


