/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { StaffResponseData } from './staffResponseData';


export interface StaffListResponse { 
    success?: boolean;
    message?: string;
    data?: Array<StaffResponseData>;
    pagination?: Pagination;
}

