/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StockResponseDataInner { 
    _id?: string;
    name?: string;
    quantity?: number;
    unit?: string;
    lowStockThreshold?: number;
}

