/**
 * KMS - Kitchen Management System API
 *
 * Contact: anas-ur-rasheed.abid@tu-ilmenau.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MealPlanItem } from './mealPlanItem';


export interface WeeklyMealPlan { 
    startDate: string;
    endDate: string;
    type: WeeklyMealPlan.TypeEnum;
    meals: Array<MealPlanItem>;
    assignedStaff: Array<string>;
    notes: string;
    createdBy: string;
}
export namespace WeeklyMealPlan {
    export const TypeEnum = {
        Week: 'week'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


